[project]
name = "appsignals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.26",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.2",
]
